In [145]:
import math
import numpy as np
import preprocess as pr
from numpy import linalg
import warnings
M = pr.M
M_test = pr.M_test
all_users = pr.all_users
all_movies = len(M[0])

min_rating = 0
max_rating = 5

In [32]:
# Евклидово расстояние между двумя точками (которые массивы)
def dist(p1, p2):
    s = 0
    for i in range(len(p1)):
        s += math.pow(p1[i] - p2[i], 2)
    return math.sqrt(s)

In [147]:
eps = 0.01
all_users = 6
m = M[:all_users]
mTr = np.transpose(m)
indexes = np.arange(all_users)

K = 2

In [148]:
m = [[1,1],[1,0],[0,2],[2,4],[3,5],[4,2]]
m

[[1, 1], [1, 0], [0, 2], [2, 4], [3, 5], [4, 2]]

In [149]:
i = 0
centroids = [np.zeros((K,2)).tolist()]
random_centroid = (np.random.randint(min_rating, max_rating + 1, size=(K,2))).tolist()
centroids.append(random_centroid)
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=RuntimeWarning)
    while linalg.norm(np.asarray(centroids[i]) - np.asarray(centroids[i + 1])) >= eps:
        print("Iteration № ", i)
        print("--------------------------------------------------")
        res = []
    
        for index in indexes:
            distances = []
            for k in range(K):
                distances.append(dist(m[index],centroids[i + 1][k]))
   
            res.append(distances)
    
        print("Distances: ", res)
        print("--------------------------------------------------")
        clusters = ([],[])#tuple([[]] * K )
    
    
        for index in indexes:
            for k in range(K - 1):
                if res[index][k] < res[index][k + 1]:
                    clusters[k].append(index)
                else:
                    clusters[k + 1].append(index)
                
        print("Clusters: ", clusters)
    
        new_centroid = []
        for c in clusters:
            cluster = [m[i] for i in c]
            if not cluster:
                new_centroid.append(np.zeros((K,2)).tolist())
            else:
                new_centroid.append((np.asarray(cluster).mean(axis = 0).tolist()))
        centroids.append(new_centroid)
        
        print("--------------------------------------------------")
        print("Centroids: ", centroids)   
            
        i += 1
#         if i == 2:
#             break
    
    

Iteration №  0
--------------------------------------------------
Distances:  [[2.23606797749979, 3.0], [2.0, 4.0], [3.605551275463989, 2.23606797749979], [4.123105625617661, 1.0], [5.0, 2.23606797749979], [2.23606797749979, 3.605551275463989]]
--------------------------------------------------
Clusters:  ([0, 1, 5], [2, 3, 4])
--------------------------------------------------
Centroids:  [[[0.0, 0.0], [0.0, 0.0]], [[3, 0], [1, 4]], [[2.0, 1.0], [1.6666666666666667, 3.6666666666666665]]]
Iteration №  1
--------------------------------------------------
Distances:  [[1.0, 2.748737083745107], [1.4142135623730951, 3.7267799624996494], [2.23606797749979, 2.3570226039551585], [3.0, 0.47140452079103173], [4.123105625617661, 1.8856180831641267], [2.23606797749979, 2.867441755680875]]
--------------------------------------------------
Clusters:  ([0, 1, 2, 5], [3, 4])
--------------------------------------------------
Centroids:  [[[0.0, 0.0], [0.0, 0.0]], [[3, 0], [1, 4]], [[2.0, 1.0], [1.66

In [130]:
centroids[2]

[[0.6666666666666666, 1.0], [2.5, 4.5]]

In [121]:
centroids[0]-centroids[1]

array([[ 0., -1.],
       [-5., -2.]])

In [45]:
w = []
for i in np.transpose(cluster):
    temp = np.sum(i) / len(i)
    w.append(temp)
len(w)

1682

In [60]:
eps = 0.0001
all_users = 5
m = M[:all_users]
mTr = np.transpose(m)
indexes = np.arange(all_users)

K = 2

In [61]:
from sklearn.cluster import KMeans
import numpy as np
# X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0],[5,6]])
X = m
kmeans = KMeans(n_clusters = K, random_state=0).fit(X)
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

In [62]:
len(labels)

5

In [101]:
np.zeros((K,2)).tolist()

[[0.0, 0.0], [0.0, 0.0]]

In [65]:
res = ([],[])
for i in range(len(X)):
    #if 
    print("coord: ", X[i], " label: ", labels[i])

coord:  [ 5.  3.  4. ...,  0.  0.  0.]  label:  1
coord:  [ 4.  0.  0. ...,  0.  0.  0.]  label:  0
coord:  [ 0.  0.  0. ...,  0.  0.  0.]  label:  0
coord:  [ 0.  0.  0. ...,  0.  0.  0.]  label:  0
coord:  [ 0.  0.  0. ...,  0.  0.  0.]  label:  0


In [21]:
clusters = ([],[])

if res[0][0] < res[0][1]:
    clusters[0].append("BLA")
else:
    clusters[1].append(0)
clusters

(['BLA'], [])

In [30]:
tuple([[]] * K )

([], [])

In [104]:
cluster

[[1, 1], [1, 0], [0, 2]]

In [105]:
np.asarray(cluster).mean(axis = 0)

array([ 0.66666667,  1.        ])

In [135]:
a = [[1,2,3],[3,4,5]]

In [136]:
np.asarray(a)

array([[1, 2, 3],
       [3, 4, 5]])

In [137]:
a

[[1, 2, 3], [3, 4, 5]]